### ISSUE TITLE
Import Error when torch_geometric is not available

### ISSUE THREAD

**Issue by zrt** [lucidrains/egnn-pytorch#30]
https://github.com/lucidrains/egnn-pytorch/blob/e35510e1be94ee9f540bf2ffea49cd63578fe473/egnn_pytorch/egnn_pytorch.py#L413

A small problem, this `Tensor` is not defined.

Thanks for your work.

**Comment by hypnopump** [comment]
For the sparse implementation, torch geometric is needed. It will not work without it.

**Comment by zrt** [comment]
But when I import this module, and want to use other functions, python still raised an error..

**Comment by jscant** [comment]
I have submitted a merge request which fixes this issue.

**Comment by hypnopump** [comment]
@jscant the PR has been merged! It will be included in the next release (hopefully today). In the meantime, you can try to clone / pull the changes and work locally @zrt
