### ISSUE TITLE
Few queries on the implementation

### ISSUE THREAD

**Issue by denjots** [lucidrains/egnn-pytorch#5]
Hi - fast work coding these things up, as usual! Looking at the paper and your code, you're not using squared distance for the edge weighting. Is that intentional? Also, it looks like you are adding the old feature vectors to the new ones rather than taking the new vectors directly from the fully connected net - is that also an intentional change from the paper?

**Comment by lucidrains** [comment]
@denjots thank you! I went back and reread the paper, and somehow in my mind I just assumed it was the norm on first glance. It has been corrected in 0.0.12!

The residual connection is actually described in appendix C under *the node function*
![Screenshot from 2021-03-01 07-45-14](https://user-images.githubusercontent.com/108653/109521464-2faa3680-7a62-11eb-89df-2095a83dc24d.png)

**Comment by denjots** [comment]
Ha ha - that residual connection was certainly well hidden in the paper!

**Comment by lucidrains** [comment]
haha yea, i didn't see it on the first pass either!
