### ISSUE TITLE
Edge features thrown out

### ISSUE THREAD

**Issue by josejimenezluna** [lucidrains/egnn-pytorch#6]
Hi, thanks for this implementation!

I was wondering if the pytorch-geometric implementation of this architecture is throwing the edge features out by mistake, as seen here

https://github.com/lucidrains/egnn-pytorch/blob/1b8320ade1a89748e4042ae448626652f1c659a1/egnn_pytorch/egnn_pytorch.py#L148-L151

Or maybe my understanding is wrong?
Cheers,

**Comment by lucidrains** [comment]
@josejimenezluna oh yes, you are correct https://github.com/lucidrains/egnn-pytorch/releases/tag/0.0.14

**Comment by josejimenezluna** [comment]
Closing this 👍
